# Generated by Django 4.1.13 on 2024-03-27 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='Another quiz!', null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='Duration of the quiz in minutes')),
                ('required_score', models.DecimalField(decimal_places=2, help_text='Score needed to pass the quiz in %', max_digits=6)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], help_text='The difficulty of the quiz', max_length=6)),
                ('category', models.ForeignKey(blank=True, help_text='The category the quiz will be about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizes', to='quiz.category')),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
    ]
