# Generated by Django 4.2.11 on 2024-03-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="number_of_questions",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="time",
            field=models.PositiveIntegerField(
                help_text="Duration of the quiz in minutes"
            ),
        ),
    ]
