# Generated by Django 5.0.3 on 2024-04-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_quiz_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
    ]
