# Generated by Django 5.0.3 on 2024-05-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_alter_quiz_number_of_questions_alter_quiz_time'),
        ('quizes', '0004_alter_quiz_number_of_questions'),
    ]

    operations = [
    ]
